# Generated by Django 4.2.7 on 2023-11-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='location',
        ),
    ]
