# Generated by Django 4.2.7 on 2023-11-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_student_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(choices=[('BN', 'Bonny Island'), ('OW', 'Owerri'), ('OL', 'Online')], default='Undecided', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
